language: rust
rust:
    - stable
    - beta
dist: trusty
sudo: false
before_script:
    # If we're testing beta or nightly, we still need to install the stable
    # toolchain so that we can run the stable version of rustfmt.
    - rustup toolchain install stable
    # Install the stable version of rustfmt.
    - rustup component add --toolchain=stable rustfmt-preview
    # Sometimes the component isn't actually ready after being installed, and
    # rustup update makes it ready.
    - rustup update
script: ./test-all.sh
