[package]
description = "A WIT test case generator"
documentation = "https://docs.rs/wit-smith"
edition.workspace = true
license.workspace = true
name = "wit-smith"
repository = "https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wit-smith"
version.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
arbitrary = { workspace = true, features = ["derive"] }
wit-component = { workspace = true }
wit-parser = { workspace = true }
clap = { workspace = true, optional = true }
indexmap = { workspace = true }
log = { workspace = true }
semver = { workspace = true }
