[package]
name = "wasm-compose"
version = "0.2.1"
edition.workspace = true
authors = ["Peter Huene <peter@huene.dev>"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
repository = "https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-compose"
homepage = "https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-compose"
documentation = "https://docs.rs/wasm-compose"
description = "A library for composing WebAssembly components."

[dependencies]
wat = { workspace = true }
wasm-encoder = { workspace = true }
wasmparser = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
anyhow = { workspace = true }
serde = { workspace = true }
petgraph = "0.6.2"
log = { workspace = true }
serde_yaml = "0.8.26"
clap = { workspace = true, optional = true }
smallvec = "1.10.0"
heck = "0.4.0"

[features]
default = []
cli = ["clap"]

[dev-dependencies]
glob = "0.3.0"
pretty_assertions = "1.2.1"
wasmprinter = { workspace = true }
