[package]
name = "host"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
clap = { version = "4.3.19", features = ["derive"] }
driftwood = "0.0.7"
tide = "0.16.0"
wasmtime = { version = "16.0", features = ["component-model"] }
wasmtime-wasi = { version = "16.0" }
wasi-cap-std-sync = { version = "16.0" }
anyhow = "1.0.72"
async-trait = "0.1.74"

[workspace]
